
[package]
name = "chaos_insurgency"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy-inspector-egui = "0.11"
fastrand = "1.7"

[dependencies.bevy-inspector-egui-rapier]
version = "0.3"
features = ["rapier2d"]

[dependencies.bevy]
version = "0.7"
features = ["dynamic"]

[dependencies.bevy_rapier2d]
version = "0.13"
features = [ "simd-nightly", "debug-render", "parallel" ]

[dependencies.bevy_asset_loader]
version = "*"
features = ["2d"]

# release build all dependencies - our code still built in debug mode by default
[profile.dev.package."*"]
opt-level = 3

# always keep bevy_rapier2d optimized even when debugging other stuff, *insane* performance difference.
[profile.dev.package.bevy_rapier2d]
opt-level = 3
